### ISSUE TITLE
change color of the tabbaritem

### ISSUE THREAD

**Issue by Dulatheo** [Cuberto/flashy-tabbar#4]
How to change color of tabbaritem?

**Comment by askopin** [comment]
firstly, you should update to 0.8.2
Next, the item color depends on bar `tintColor`, there is some strange behavior - `tintColor` of standard UITabBar doesn't sets from storyboard. So, there is two way to solve your problem: set `tintColor` property from code (directly, or using `UIAppearance`) or set  `CBFlashyTabBar` class to TabBar in storyboard and set tintColor in interface builder
