### ISSUE TITLE
Edit font size of tabbaritem

### ISSUE THREAD

**Issue by Dulatheo** [Cuberto/flashy-tabbar#5]
How can I edit the font size of tabbaritem title?

**Comment by OlivierMrz** [comment]
Hi, the font of the tabbar item won't change.. 🤔
What is the best approach to do so?

**Comment by askopin** [comment]
We solved this trouble and integrated this animation in new control: https://github.com/Cuberto/cb-tabbar
I think it's more comfortable to have all tabbar animations in one place
P.S. subclass `UITabBarItem` and conform `CBExtendedTabItem`
