### ISSUE TITLE
Badge display

### ISSUE THREAD

**Issue by gmckee1** [Cuberto/flashy-tabbar#6]
Hi,

There seems to be an issue displaying the badge on the tab bar. The following code correctly sets the tab item badge value, but it doesn't seem to be display.

`if let tabItems = tabBarController?.tabBar.items {
            let tabItem = tabItems[2]
            tabItem.badgeValue = "3"
}`

I've had a look through the CBTabBarButton code, but can't see where error is.

**Comment by askopin** [comment]
We solved this trouble and integrated this animation in new control: https://github.com/Cuberto/cb-tabbar
I think it's more comfortable to have all tabbar animations in one place

**Comment by Dellybro** [comment]
How does this fix the issue? It still doesn't seem to show the badge value

**Comment by lex-shvets** [comment]
@Dellybro use CBTabBarController instead and apply flashy style :)

**Comment by FugenApps** [comment]
Can you give us an example?

**Comment by lex-shvets** [comment]
<img width="866" alt="Screenshot 2019-03-30 at 18 00 14" src="https://user-images.githubusercontent.com/26301411/55279167-b5bd2000-5315-11e9-8170-e77bef747ec9.png">


> Can you give us an example?

**Comment by FugenApps** [comment]
I can't install CBTabBarController via cocoapods for some reason i get this error 

[!] Unable to find a specification for `CBTabBarController`

**Comment by FugenApps** [comment]
Something was wrong with my cocoapods master repo, it works now. Sorry
