### ISSUE TITLE
Safearea bottom and Height of Tabbar and Badge Value

### ISSUE THREAD

**Issue by Dellybro** [Cuberto/flashy-tabbar#7]
The safe area doesn't seem to work with the height of the tabbar. The tabBar is taller then the safeArea bottom which overlaps my views. 

The badge Value also doesn't appear when i set badgeValue = "NEW" on any tabbar item.

**Comment by ShvetsJr** [comment]
I am having the exact same issue.. :( Would be nice to get help on tabbar height

**Comment by askopin** [comment]
safe area behavior fixed in version 8.3
To not 'multiply entities without necessity' we decided to keep all our tab bar animations in one place: https://github.com/Cuberto/cb-tabbar 
Flashy style exactly matches this component behavior and it supports badges (probably i'll port it to this repo but not today)

**Comment by FugenApps** [comment]
@askopin I just tested CBTabBarController with flashy it works! That's good news, but the badgeValue doesn't show up.

**Comment by askopin** [comment]
@FugenApps check master branch

**Comment by FugenApps** [comment]
@askopin 

Does this mean it's not uploaded on cocoapods and i'll have to checkout the master branch to get the latest updates?

My current version is 

CBTabBarController (0.9.3)

**Comment by FugenApps** [comment]
@askopin 

My pod file for CBTabBarController has 
`pod 'CBTabBarController', :git => 'https://github.com/Cuberto/cb-tabbar.git', :branch => 'master'`

but unfortunately when i called 

`self.tabBarItem.badgeValue = "NEW";`

I get no badge on the tabbar, heres a screenshot,

<img width="331" alt="Screen Shot 2019-03-30 at 5 27 29 PM" src="https://user-images.githubusercontent.com/17523904/55283148-53fab700-5311-11e9-8d6e-28dfeb6f3ce8.png">

**Comment by askopin** [comment]
@FugenApps i forgot to push changes, check now.

**Comment by FugenApps** [comment]
@askopin Thanks! It works! Just want to say i love your stuff and can't wait to use more of it! Very simplistic frameworks that do most of the heavy lifting for you!

**Comment by lex-shvets** [comment]
It’s indeed amazing, thank you!
