### ISSUE TITLE
How to change the color of the tab bar. 

### ISSUE THREAD

**Issue by Jaystiqs** [Cuberto/flashy-tabbar#8]
My application is dark and the tab bar is white. How do you change the color of the tab bar?
CBFlashyTabBar.appearance() doesn't work. Neither does the bar tint color on storyboard

**Comment by askopin** [comment]
fixed this bug, both ways should work now.
P.S. to not 'multiply entities without necessity' we decided to keep all our tab bar animations in one place: https://github.com/Cuberto/cb-tabbar (flashy style exactly matches this component behavior)
